###################  项目启动端口  ###################
server:
  port: 81
###################  任务计划配置  ###################
zookeeper:
    serverLists: 10.16.37.112:3181
    namespace: weixiao
###################  spring配置  ###################
spring:
  profiles:
      active: TEST
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    prefer-file-system-access: false
gensee :
    organiser:
      id: 45346731
      loginName: zrwxorganiser
      password: h9egYiWC5Z
      url: http://zrw.gensee.com/integration/site
    admin:
      id: dsd
      loginName: zrwxadmin
      password: h9egYiWC5Z
---
##########################################################
###################  测试环境的profile  ###################
##########################################################
domain: http://weixiao.t.ziroom.com/
spring:
  profiles: TEST
  datasource:
      domian: 10.16.16.13:3306
      databaseName: weixiao
      username: bsrd_weixiao_user
      password: ziroomdb
  redis :
      cluster:
          nodes: 10.16.34.125:6392,10.16.34.125:6393,10.16.34.125:6394
      master:
          name: sentinel-10.16.34.125-6390
      pool:
            max-idle: 100
            min-idle: 1
            max-total: 1024
            max-wait: 1000
  cas:
      url: http://cas.ziroom.com/CAS
techplatform:
  storage:
      url: http://storage.t.ziroom.com
      storageaccessurl: http://172.16.13.222
      storagefileaccessurl: http://10.16.34.48:8080
  mail:
        url: http://message.t.ziroom.com
        token: DPSK6R4eRem98jyydaSomA
  sms:
        url: http://message.t.ziroom.com
        token: YRQ4NqJ5Ra2nYuMGRmcSlQ
bsrd:
    ehr:
        url: http://ehrnew.t.ziroom.com 
    cms:
        url: http://contentful.inside.ziroom.com
    push:
        url: http://api.push.t.ziroom.com/push
        gj_token: 151bb942d4214102b0d99513713805b5
        pz_token: a66b9021e4ab48bcbf94119d81e6e2b8

---
