###################  项目启动端口  ###################
server:
  port: 82
###################  spring配置  ###################
rpc:
  server:
        port: 8087
  zookeeper:
        serverLists: 10.16.37.112:3181
        rpcnamespace: rpctest
###################  rpc  ###################
spring:
  profiles:
      active: TEST
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    prefer-file-system-access: false
---
##########################################################
###################  测试环境的profile  ###################
##########################################################
domain: http://weixiao.t.ziroom.com/
spring:
  profiles: TEST
  redis:
        host: tech.t.ziroom.com
        pool:
            max-idle: 100
            min-idle: 1
            max-total: 1024
            max-wait: 1000
        sentinel:
            master: sentinel-10.16.34.125-6390
            nodes: 10.16.34.125:6392,10.16.34.125:6393,10.16.34.125:6394

---
